### ISSUE TITLE
Datasette: update log/stamp

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/iati-tables#3]
Currently on https://datasette.codeforiati.org/ we can't readily access the lastupdate dateTime - which we know is at https://iati-tables.codeforiati.org/

**Comment by stevieflow** [comment]
maybe also point to https://ocdsdata.opendataservices.coop/tree?dag_id=run-iati&root= in both instances (@kindly : should / could we put this process in its own Airflow? Does that make any sense?)

**Comment by kindly** [comment]
It was not worth the effort of making a whole new airflow instance for this task and why I did not do it.

There may be value in a code-for-iati airflow instance where lots of the long running tasks are managed as at the moment everyone has there own not very transparent cron jobs. 

All the logs are stored in the S3 bucket and I need to think of a good way of gettting the iati-tables website and datasette.

I also would need to work out how to customise datasette a bit before any information could be displayed in it.

**Comment by odscjames** [comment]
> Currently on https://datasette.codeforiati.org/ we can't readily access the lastupdate dateTime

We can create a special meta table and write it to that. It won't be totally obvious in the UI but people can still do a couple of clicks / 1 simple SQL and see the value.

**Comment by tillywoodfield** [comment]
There is now a table called `metadata` in datasette and all the other output formats containing two columns `data_dump_updated_at` (taken from the IATI data dump used for processing), `iati_tables_updated_at` (the time when Tables processed the data)
