### ISSUE TITLE
Add column for what dataset an activity has come from

### ISSUE THREAD

**Issue by Bjwebb** [codeforIATI/iati-tables#33]
The dataset name looks something like `undp-abw`, and is useful because people can look that up on the registry to find the url and other info https://iatiregistry.org/dataset/undp-abw

The data that iati-tables loads via iatikit has filenames named with the dataset (e.g. `undp-abw.xml`), so we should be able to get it from there.

I think we possibly want to add this as a column to every table.

**Comment by tillywoodfield** [comment]
Column `dataset` has now been added to all tables
