### ISSUE TITLE
numbers with trailing 0 don't format in csv export 

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/iati-tables#36]
This isn't strictly a bug or the fault of IATI Tables - but wanted to log and see if there may be a way around it

Example

Some publishers have poorly constructed organisation references in their data, that start with a 0 or three:

[Example activity](https://d-portal.org/ctrack.html?/participating-org@ref=00010#view=act&aid=XM-DAC-41114-OUTPUT-00113437):

![Firefox_Screenshot_2024-02-22T12-40-20 607Z](https://github.com/codeforIATI/iati-tables/assets/1209944/8790ebad-0bbc-4aac-b9cb-76e781bef977)

In tables [datasette](https://datasette.codeforiati.org/iati/participatingorg?_sort=rowid&narrative__contains=Institute+for+Environ+and+Dev), this is as published:

![Firefox_Screenshot_2024-02-22T12-41-16 774Z](https://github.com/codeforIATI/iati-tables/assets/1209944/de224b39-20df-4458-b042-ac1bd97d8156)

If I then download the CSV for that query, the 0010 opens as 10

I know this is a spreadsheet issue - but wondered if there is anything that can be done in the export file?

Note - whilst this org reference is *invalid* it is useful to work with and analyse, to then give feedback

**Comment by robredpath** [comment]
This is actually correct in [the CSV](https://datasette.codeforiati.org/iati/participatingorg.csv?_sort=rowid&narrative__contains=Institute+for+Environ+and+Dev&_labels=on&_size=max), so this is a result of spreadsheet software interpreting 00010 as a number. How silly of it!
 
<img width="929" alt="Screenshot 2024-02-22 at 12 51 21" src="https://github.com/codeforIATI/iati-tables/assets/641009/df1b93ea-1359-4991-ac7f-7482efd24094">

Is there anything we can do to make the CSV give better hints about how to treat this column? Or [offer xlsx](https://github.com/vitlais/datasette-render-xlsx) ? 

I feel like this is something that asking around the co-op would get lots of useful experience and stories around!

**Comment by stevieflow** [comment]
thanks @robredpath @tillywoodfield yeah, it's something to work with/around

Ill try that too @tillywoodfield 

I guess this might be more of a documentation issue, eventually @robredpath ?

**Comment by tillywoodfield** [comment]
@stevieflow @robredpath I've added this to the [IATI Tables Docs](https://iati-tables.readthedocs.io/en/latest/usage/#disable-auto-formatting), are you happy for us to close the issue?

**Comment by stevieflow** [comment]
Excellent, thanks @tillywoodfield !
