### ISSUE TITLE
[IDEA] Analytics / Publisher-Stats table?

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/iati-tables#6]
Wasn't exactly sure where to log this -- but something for @kindly @andylolz @matmaxgeds to think on

Is there any use/value in pulling in the data/stats behind Analytics / Publisher-Stats into iati-tables?  Could this be useful for queries?

**Comment by kindly** [comment]
I would be wary of this, as the Stats from exernal sources into iat-tables as the numbers would never match up exactly as the data would not be taken at the same time and some assumptions would not be exactly the same either.

I would be happy to reproduce some of the useful stats as another step in the output.

**Comment by andylolz** [comment]
> I would be wary of this, as the Stats from exernal sources into iat-tables as the numbers would never match up exactly as the data would not be taken at the same time and some assumptions would not be exactly the same either.

^^ totally agree. It’s probably possible to create a colab that reproduces most of the stats, but using the iati-tables database as the source.

**Comment by odscjames** [comment]
I'm going to close this - I agree pulling from external sources is going to have a mismatch and running stats ourself is better. If people have ideas about specific stats they would find useful, please open a new issue for each one and we'll see if we can add them.
