### ISSUE TITLE
[IDEA] Extend IATI Tables to cover Org files

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-tables#8]
moved over from [here](https://github.com/codeforIATI/iati-ideas/issues/46)

## Rationale
[IATI tables](https://iati-tables.codeforiati.org/) are great when you need to do some analysis that is not common enough to have a specific tool. Org files have very few tools that provide the info they include, the only options are using [iati-decipher](https://decipher.codeforiati.org/#) (publisher by publisher) or the registry/data dump and dealing with parsing all the xml.

## Proposal
Add org files to IATI-tables

**Comment by stevieflow** [comment]
@tillywoodfield it would be good to discuss this, as I agree it would be a very good addition

One thing I don't know - @Bjwebb may be able to help  - is whether org files are in the data dump source...

**Comment by tillywoodfield** [comment]
@stevieflow, yes I think they are included in the data dump already, and [iatikit](https://github.com/codeforIATI/iatikit) (which Tables uses to interact with the activity files) also seems to support organisation files, so it should be possible

**Comment by stevieflow** [comment]
Good news, thanks @tillywoodfield 

There are nine *top-level* data fields in the [org standard](https://iatistandard.org/en/iati-standard/203/organisation-standard/) so it will certainly end up in far less tables than the activity data (and there's far far less organisations, too).  

A thing I am very interested in is the [organisation-identifier](https://iatistandard.org/en/iati-standard/203/organisation-standard/iati-organisations/iati-organisation/organisation-identifier/) table, in terms of understanding how canonical or useful it might be

But the budgets and documents will be very interesting too

**Comment by matmaxgeds** [comment]
Watching with interest/gratitude for the work - org-id's defo also my interest, including the 2.01 and prev. versions, and whether there is any way to pickup publishers transitioning across/between old/new orgs!

**Comment by stevieflow** [comment]
Thanks @matmaxgeds - great to hear from you!

**Comment by tillywoodfield** [comment]
@stevieflow @matmaxgeds, you should now be able to find organisation file data under the top level `organisation` table and child `organisation_*` tables.

The `<organisation-identifier>` element can be found in table `organisation`, column `organisationidentifier`.

Let me know if you see anything that doesn't look right or have any feedback! :)

**Comment by stevieflow** [comment]
Amazing, thanks @tillywoodfield 

I had a quick check and all seems in order
